### ISSUE TITLE
[BUG] The clipboard icon duplicated to two in the top bar

### ISSUE THREAD

**Issue by Tallin-Boston-Technology** [gustavosett/Windows-11-Clipboard-History-For-Linux#47]
## 🐛 Bug Description

This bug has existed since version 0.3.2 and its that the clipboard icon at the top-right taskbar in my ubuntu 24.04. ive attached a screenshot and sorry if i dont know how else to describe it. the left icon in the screenshot is unresponsive as in its only present there and is not clickable, the second clipboard icon works though

## ✅ Expected Behavior

im assuming that only one of them is suppose to work but there are two icons and only the second icon works.

## 📸 Screenshots

<img width="246" height="111" alt="Image" src="https://github.com/user-attachments/assets/042fdef6-71a8-4722-9656-3e8006ea2776" />

## 🖥️ Environment

# System Details Report
---

## Report details
- **Date generated:**                              2025-12-22 13:42:08

## Hardware Information:
- **Hardware Model:**                              HP HP EliteBook 840 G3
- **Memory:**                                      20.0 GiB
- **Processor:**                                   Intel® Core™ i5-6200U × 4
- **Graphics:**                                    Intel® HD Graphics 520 (SKL GT2)
- **Disk Capacity:**                               256.1 GB

## Software Information:
- **Firmware Version:**                            N75 Ver. 01.52
- **OS Name:**                                     Ubuntu 24.04.3 LTS
- **OS Build:**                                    (null)
- **OS Type:**                                     64-bit
- **GNOME Version:**                               46
- **Windowing System:**                            Wayland
- **Kernel Version:**                              Linux 6.14.0-37-generic

## 📄 Logs

<details>
<summary>Click to expand logs</summary>

```
Paste any relevant logs here
```

</details>

**Comment by Tallin-BTC** [comment]
Another think that i would like to add is that the left icon sometimes jumps to the top-left of the screen. the way to recreate this is by locking your laptop by super + L and when you log back in the left icon(unresponsive one) is at the very top-left of the screen, this is the case in any resolution that ive tried and ive attached a screenshot for reference.

<img width="294" height="124" alt="Image" src="https://github.com/user-attachments/assets/97522106-f494-4e30-99b8-6a22431e51c2" />

**Comment by gustavosett** [comment]
Hey @Tallin-Boston-Technology 
Interesting, could you update to the latest version to see if it still happens in the most recent version?

```bash
curl -fsSL https://raw.githubusercontent.com/gustavosett/Windows-11-Clipboard-History-For-Linux/master/scripts/install.sh | bash
```

**Comment by gustavosett** [comment]
It's fixed for me in 0.4.8, could you try it out, please? I see that you closed some minutes ago but it's better to test the latest version that I just deployed 🤠

**Comment by Tallin-BTC** [comment]
its still there.......i swear it was fixed just a minute ago, i saw that youve released a new ver. so i just updated it and continued on working because i saw that it was removed now but after your msg i checked by trying to recreate with super + L and logging back in......and it reappeared. I swear it was fixed but now it reappeared, i apologize for wasting so much of your time that might just be my own laptop's fault, i wont reopen this issue if you ask me to because i think that there is a high possibility that this might just be my fault.

<img width="890" height="240" alt="Image" src="https://github.com/user-attachments/assets/0f1fea3b-bc8f-487e-aecd-090dc26582c4" />

Also thank you for your efforts, i would have recommended your clipboard to my coworkers as well but they are on windows. I hope i see more of your projects in linux.

**Comment by gustavosett** [comment]
I'm so sorry @Tallin-Boston-Technology maybe I said to you download a wrong PPA repository name, please you need to fix it. I already released the hotfix

the repository namespace has been renamed from workspace-for-gustavo to gustavosett.

If you see a 404 Not Found or The repository... no longer has a Release file error when running sudo apt update, you need to update your repository configuration.

How to fix it
Run the following command in your terminal. It will safely remove the old configuration and install the new one:

```bash
grep -l "workspace-for-gustavo" /etc/apt/sources.list.d/* | xargs sudo rm -f && \
curl -fsSL https://raw.githubusercontent.com/gustavosett/Windows-11-Clipboard-History-For-Linux/master/scripts/install.sh | bash
```

now sudo apt update and upgrade will works, you don't need to update manually anymore :)

**Comment by Tallin-BTC** [comment]
E: The repository 'https://dl.cloudsmith.io/public/workspace-for-gustavo/clipboard-manager/deb/ubuntu noble Release' no longer has a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

i did as you told me and sudo apt update 'd it but it is saying it was dismissed. also the old duplicated icons are back

<img width="890" height="240" alt="Image" src="https://github.com/user-attachments/assets/6697597a-b732-45d7-aec9-4021c0290179" />

the only way they show up, that ive noticed, is if i lock my laptop and reopen it, it doesnt happen anyother time or happen randomly

**Comment by gustavosett** [comment]
I am so sorry, @Tallin-Boston-Technology! Please don't feel bad — this is 100% on me. I realized I gave you a command that didn't fully clear the old repository settings, which is why your system is still seeing the 404 error and the old icons.

The error happens because Linux is trying to update from a 'ghost' address that no longer exists. Since the update fails, the bug fix (version 0.4.8) never actually gets installed on your machine.

Let's fix this for real. Please run this specific command (it will find the old file and replace it with the new one):

```bash
sudo grep -l "workspace-for-gustavo" /etc/apt/sources.list.d/* | xargs sudo rm -f && \
curl -fsSL https://raw.githubusercontent.com/gustavosett/Windows-11-Clipboard-History-For-Linux/master/scripts/install.sh | bash
```
After that, just run: sudo apt update

You should see that the error is gone. Once the error is gone, your system will finally download the fix for the duplicate icons.

Thank you for being so patient while I iron out these migration details! You are actually helping me a lot by reporting this. 🤠

**Comment by gustavosett** [comment]
Reference:
https://github.com/gustavosett/Windows-11-Clipboard-History-For-Linux/commit/0609211bba9c2bb14faccd28a8c5c104d54e1ceb

**Comment by Tallin-BTC** [comment]
the repository download is fixed but the duplicate still persists.

i have tried this:
sudo grep -l "workspace-for-gustavo" /etc/apt/sources.list.d/* | xargs sudo rm -f && \
curl -fsSL https://raw.githubusercontent.com/gustavosett/Windows-11-Clipboard-History-For-Linux/master/scripts/install.sh | bash

and this:
sudo apt update

and ive restarted the laptop but the duplicate reappeared. Should i reopen this issue if you want me to 😥?

**Comment by gustavosett** [comment]
I'm analyzing it 🤔

**Comment by gustavosett** [comment]
@Tallin-Boston-Technology fixed, it was a race condition during system startup; the clipboard was attempting to start before the interface was 100% ready. Please run the update and upgrade.

**Question**: Did this happen previously even after clicking quit and restarting the clipboard using the shortcut keys?

Thank's for helping a lot with this issue, when we had credits for contribution I'll put your name there. 

Oh, let me know if it works 🤠

**Comment by Tallin-BTC** [comment]
Hi @gustavosett , sorry for the late reply and to answer your question is that no its **still persisting** and i dont know why. 

To answer your second question is that whenever i locked my laptop with super + L, the duplicate icons shows up so yes this happened previously but what you got wrong is that as soon as i restarted my laptop, **the clipboard runs on its own so im assuming its a startup application**; anyways because of that the clipboard runs on its own and opens the clipboard automatically on restart and the duplicate icon shows up even before i try to use the shortcut. So im assuming because its a startup application that runs on its own on reboot, its duplicating it selves? thats what ive notices so far is that it starts on reboot on its own and causes the duplicate to occur even before i try to open the clipboard and this only happens whenever i lock my laptop and log back in, **this does not happen when i do a complete shut down/restart**. 

Also **please dont credit my name** since i am only a user of it and that it was convenient and beneficial for my field of work 😅😅, what you did will benefit a lot more people so you should only consider crediting their name since they ACTUALLY helped

<img width="264" height="182" alt="Image" src="https://github.com/user-attachments/assets/c401e5d3-56ca-49e5-957b-a101ec587980" />

**Comment by Tallin-BTC** [comment]
another think that i would like to add is that when ever i update to the latest ver. of this, the duplicate disappears even when its currently present on screen, but as soon as i lock and log back in it shows back as well. So maybe it has something to do with how it starts or how it is handled on initial startup?🤔 but other that this annoying duplication everything else works exactly as intended; the only time it doesnt work is with the terminal and its ^V bug, any other application works perfectly for this.

**Comment by gustavosett** [comment]
@Tallin-Boston-Technology are you using 0.4.15 version?

```bash
➜  win11-clipboard-history --version
win11-clipboard-history 0.4.15
```

if not please, run apt update and upgrade

**Comment by Tallin-BTC** [comment]
yes @gustavosett it says that it is 0.4.15 specifically because i always check to see if i have the latest version installed after running an update and i did just now as well

<img width="778" height="183" alt="Image" src="https://github.com/user-attachments/assets/bdef8014-5c4b-43cb-9df1-bdf4c078b6ac" />
